sudo: required
services:
  - docker

before_install:
  - docker build -t richardpentecost/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true richardpentecost/docker-react npm run test
